"""
Plots cores vs time collected from output/timings.txt generated by Assignment3.sh
"""
import matplotlib.pyplot as plt

def plotter(file):
    """
    Reads in the thread-time file and creates timings.png
    Threads are on the x axis
    Times are on the y axis
    """
    
    # list to hold thread timings
    threadtimes = []
    
    # opens the file to extract the data
    with open(file, "r", encoding = "utf8") as data:
        for line in data:
            if line[0].isdigit():
                threadtimes.append(line.strip().split(":"))
    
    # separate the values to times and threads
    thread = [x[1] for x in threadtimes]
    time = [x[0] for x in threadtimes]
    
    # plot the values and save to file
    plt.scatter(time, thread)
    plt.title("Time vs number of threads")
    plt.xlabel("Number of threads")
    plt.ylabel("Running time")
    plt.savefig("output/timings.png")

if __name__ == "__main__":
    plotter("output/timings.txt")
